/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.rudyreyes.javacraft.vista;

import com.rudyreyes.javacraft.modelo.errores.Errores;
import java.util.LinkedList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author rudyo
 */
public class VentanaReportes extends javax.swing.JDialog {

    LinkedList<Errores> listaErrores;
    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes(java.awt.Frame parent, boolean modal, LinkedList<Errores> lista) {
        super(parent, modal);
        this.listaErrores = lista;
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTablaErrores = new javax.swing.JButton();
        btnTablaSimbolos = new javax.swing.JButton();
        btnGenerarAST = new javax.swing.JButton();
        scrollTablaReportes = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes JavaCraft");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");

        btnTablaErrores.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnTablaErrores.setText("Tabla de Errores");
        btnTablaErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaErroresActionPerformed(evt);
            }
        });

        btnTablaSimbolos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnTablaSimbolos.setText("Tabla de Simbolos");
        btnTablaSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSimbolosActionPerformed(evt);
            }
        });

        btnGenerarAST.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnGenerarAST.setText("Generar AST");

        scrollTablaReportes.setBackground(new java.awt.Color(255, 255, 255));

        tablaReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaReportes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollTablaReportes.setViewportView(tablaReportes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTablaSimbolos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerarAST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTablaErrores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollTablaReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTablaErrores)
                        .addGap(61, 61, 61)
                        .addComponent(btnTablaSimbolos)
                        .addGap(60, 60, 60)
                        .addComponent(btnGenerarAST))
                    .addComponent(scrollTablaReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTablaErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaErroresActionPerformed
        // TODO add your handling code here:
        String[] columnas = {"#", "Tipo", "Descripción", "Línea", "Columna"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        tablaReportes.setModel(modelo);
        
        TableColumnModel columnModel = tablaReportes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(35); // Ancho preferido para la columna "#"
        columnModel.getColumn(1).setPreferredWidth(150); // Ancho preferido para la columna "Tipo"
        columnModel.getColumn(2).setPreferredWidth(300); // Ancho preferido para la columna "Descripción"
        columnModel.getColumn(3).setPreferredWidth(50); // Ancho preferido para la columna "Línea"
        columnModel.getColumn(4).setPreferredWidth(50); // Ancho preferido para la columna "Columna"
        
        int contador = 1;
        for(var i : listaErrores){
            modelo.addRow(new Object[]{
                   contador,
                   i.getTipo(),
                   i.getDescripcion(),
                   i.getLinea(),
                   i.getColumna()
                });
            
            contador++;
        }
        
        
    }//GEN-LAST:event_btnTablaErroresActionPerformed

    private void btnTablaSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSimbolosActionPerformed
        // TODO add your handling code here:
         String[] columnas = {"#","Id", "Tipo","Tipo de Dato", "Entorno" ,"Valor", "Línea", "Columna"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        
        tablaReportes.setModel(modelo);
    }//GEN-LAST:event_btnTablaSimbolosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarAST;
    private javax.swing.JButton btnTablaErrores;
    private javax.swing.JButton btnTablaSimbolos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollTablaReportes;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
}
